apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myblog
  namespace: myblog-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Enable ssl-redirect when we arent using Cloudflare Tunnel.
    # Disable when we are using Cloudflare Tunnel, this will fix too many redirection error.
    haproxy.org/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: prod
  tls:
    - hosts:
        - hendrywilliam.com
      secretName: myblog-tls
  rules:
    - host: hendrywilliam.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myblog
                port:
                  number: 80
